### PR TITLE
fix: use meta's value_type to generate typespec

### PR DESCRIPTION
**Pull request by fishtreesugar**

### CODE REVIEW

**Comment by bitwalker** [comment]
Sorry for the delay! Would you mind adding a test that would have failed without this fix? What I have in mind is that we'd take the AST output, stringify it and then assert against the string, that should make for readable tests and can be reused for other such tests in the future.

**Comment by fishtreesugar** [comment]
@bitwalker just add a clumsy test which expose some implementation detail 😅

**Review by bitwalker — APPROVED** [review]
LGTM! Thanks for putting that test together :)

**Comment by fishtreesugar** [comment]
@bitwalker I would like to cut a new release for this, our codebase already use a fork for a long time  🙏🏻

**Comment by bitwalker** [comment]
@fishtreesugar Already done :)

**Pull request merged**
